/*
 * File: app/view/AddAtribute.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.AddAtribute', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.field.HtmlEditor',
        'Ext.form.field.Date',
        'Ext.button.Button'
    ],

    width: 676,
    layout: 'anchor',
    bodyPadding: 20,
    title: 'ატრიბუტის დამატება',
    titleAlign: 'center',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'დასახელება'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    fieldLabel: 'ტიპი',
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    hidden: true
                },
                {
                    xtype: 'htmleditor',
                    anchor: '100%',
                    height: 150,
                    hidden: true
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    hidden: true
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 2
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'გაუქმება'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 5',
                                    text: 'შენახვა'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});