/*
 * File: app/view/AddProduct.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.AddProduct', {
    extend: 'Ext.window.Window',
    alias: 'widget.addproduct',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    height: 225,
    width: 600,
    iconCls: 'icon-add',
    title: 'საქონლის დამატება',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            keyMapConfig: {
                bindings: [
                    {
                        ctrl: false,
                        key: Ext.EventObject.ENTER,
                        btnItemId: 'btnSave'
                    }
                ]
            },
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'txtName',
                    margin: '10 10 10 10',
                    fieldLabel: 'დასახელება',
                    labelWidth: 180,
                    allowBlank: false,
                    selectOnFocus: true
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    itemId: 'txtInputPrice',
                    margin: '0 10 10 10',
                    fieldLabel: 'ასაღები ფასი',
                    labelWidth: 180,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    itemId: 'txtOutputPrice',
                    margin: '0 10 10 10',
                    fieldLabel: 'გასაყიდი ფასი',
                    labelWidth: 180,
                    allowBlank: false
                },
                {
                    xtype: 'combobox',
                    storeClassName: 'SIS.store.AllSizeUnitStore',
                    itemId: 'cmbSizeUnits',
                    margin: '0 10 10 10',
                    fieldLabel: 'ზომის ერთეული',
                    labelWidth: 180,
                    allowBlank: false,
                    editable: false,
                    displayField: 'Name',
                    store: 'AllSizeUnitStore',
                    valueField: 'ID'
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    itemId: 'txtNeto',
                    margin: '0 10 10 10',
                    fieldLabel: 'მასა',
                    labelWidth: 180
                },
                {
                    xtype: 'checkboxfield',
                    itemId: 'chckDeleted',
                    margin: '0 10 10 195',
                    fieldLabel: '',
                    boxLabel: 'გაუქმება'
                },
                {
                    xtype: 'container',
                    margin: '30 10 10 10',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            margin: '0 10 0 0',
                            iconCls: 'icon-save24',
                            scale: 'medium',
                            text: '',
                            tooltip: 'შენახვა',
                            listeners: {
                                click: {
                                    fn: me.onBtnSaveClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            iconCls: 'icon-close24',
                            scale: 'medium',
                            text: '',
                            tooltip: 'გაუქმება',
                            listeners: {
                                click: {
                                    fn: me.onBtnCloseClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onBtnSaveClick: function(button, e, eOpts) {
        var form = button.up('addproduct');

        if(form.validate())
        {
            if(Ext.isFunction(form.save))
            {
                var result = form.save(form.getRecord());

                form.suspendEvents();
                form.close();
            }
        }
    },

    onBtnCloseClick: function(button, e, eOpts) {
        var form = button.up('addproduct');

        form.close();
    },

    validate: function() {
        var form = this;
        var txtName = FindControl(form, 'txtName');
        var txtInputPrice = FindControl(form, 'txtInputPrice');
        var txtOutputPrice = FindControl(form, 'txtOutputPrice');
        var cmbSizeUnits = FindControl(form, 'cmbSizeUnits');

        var valid = true;

        valid = valid && txtName.validate();
        // valid = valid && txtInputPrice.validate();
        // valid = valid && txtOutputPrice.validate();
        valid = valid && cmbSizeUnits.validate();

        return valid;
    },

    setRecord: function() {
        var form = this;
        var txtName = FindControl(form, 'txtName');
        // var txtInputPrice = FindControl(form, 'txtInputPrice');
        // var txtOutputPrice = FindControl(form, 'txtOutputPrice');
        var cmbSizeUnits = FindControl(form, 'cmbSizeUnits');
        // var txtNeto = FindControl(form, 'txtNeto');
        var chckDeleted = FindControl(form, 'chckDeleted');

        var model = form.formModel;

        if(IsNullOrEmpty(model))
        {
            form.formModel = Ext.create('SIS.model.CustomerModel');
        }
        else
        {
            txtName.setValue(model.get('Name'));
        //     txtInputPrice.setValue(model.get('InputPrice'));
        //     txtOutputPrice.setValue(model.get('OutputPrice'));
            cmbSizeUnits.setValueSafe(model.get('SizeUnitID'));
        //     txtNeto.setValue(model.get('Neto'));
            chckDeleted.setValue(model.get('Deleted'));
        }
    },

    getRecord: function() {
        var form = this;
        var txtName = FindControl(form, 'txtName');
        // var txtInputPrice = FindControl(form, 'txtInputPrice');
        // var txtOutputPrice = FindControl(form, 'txtOutputPrice');
        var cmbSizeUnits = FindControl(form, 'cmbSizeUnits');
        // var txtNeto = FindControl(form, 'txtNeto');
        var chckDeleted = FindControl(form, 'chckDeleted');

        var model = form.formModel;

        model.set('Name', txtName.getValue());
        // model.set('InputPrice', txtInputPrice.getValue());
        // model.set('OutputPrice', txtOutputPrice.getValue());
        model.set('SizeUnitID', cmbSizeUnits.getValue());
        // model.set('Neto', txtNeto.getValue());
        model.set('Deleted', chckDeleted.getValue());

        return model;
    }

});