/*
 * File: app/view/AddSizeUnit.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.AddSizeUnit', {
    extend: 'Ext.window.Window',
    alias: 'widget.addsizeunit',

    requires: [
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.Panel'
    ],

    height: 170,
    width: 390,
    title: 'ზომის ერთეულის დამატება',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            keyMapConfig: {
                bindings: [
                    {
                        ctrl: false,
                        key: Ext.EventObject.ENTER,
                        btnItemId: 'btnSave'
                    }
                ]
            },
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'txtName',
                    margin: '10 10 10 10',
                    fieldLabel: 'დასახელება',
                    allowBlank: false
                },
                {
                    xtype: 'container',
                    margin: '45 10 10 10',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form = button.up('addsizeunit');

                                var txtName = FindControl(form, 'txtName');

                                var model = Ext.create('SIS.model.SizeUnitModel');

                                if(form.validate())
                                {
                                    model.set('Name', txtName.getValue());

                                    if(Ext.isFunction(form.save))
                                    {
                                        form.save(model);

                                        form.close();
                                    }
                                }
                            },
                            itemId: 'btnSave',
                            margin: '0 5 0 0',
                            iconCls: 'icon-save24',
                            scale: 'medium',
                            text: '',
                            tooltip: 'დამატება'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form = button.up('addsizeunit');

                                form.close();
                            },
                            itemId: 'btnClose',
                            iconCls: 'icon-close24',
                            scale: 'medium',
                            text: '',
                            tooltip: 'დახურვა'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 1,
                    header: false
                },
                {
                    xtype: 'form',
                    flex: 1,
                    header: false
                }
            ]
        });

        me.callParent(arguments);
    },

    validate: function() {
        var form = this;
        var txtName = FindControl(form, 'txtName');

        var valid = true;

        valid = valid && txtName.validate();

        return valid;
    }

});