/*
 * File: app/view/DateRangeSelector.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.DateRangeSelector', {
    extend: 'Ext.form.field.Trigger',
    alias: 'widget.daterangefield',

    pickerClassName: 'SIS.view.DateRangeSelectorForm',
    emptyText: 'დაბადების თარიღი',
    editable: false,

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    },

    onTriggerClick: function() {


        console.log('select date range');

        var me = this;
        var beforeStr = this.beforeValueText || this.emptyText || '';

        var win = Ext.create(this.pickerClassName, {
            modal:true,
            save: function(rangeModel){

                if(rangeModel.get('FromDate')!=null && rangeModel.get('ToDate')!=null)
                {
                    if(this.dateRange.get('FromDate')>=this.dateRange.get('ToDate'))
                    {
                        alert('არასწორი შუალედი');

                    }


                    else
                    {
                        var fromstr = DateFormat(rangeModel.get('FromDate'), null);
                        var tostr = DateFormat(rangeModel.get('ToDate'), null);
                        rangeModel.set('Range',  fromstr + ' ' + '-' + ' '+ tostr);
                        me.setValue(beforeStr+': '+rangeModel.get('Range'));
                        me.fromDate = rangeModel.get('FromDate');
                        me.toDate = rangeModel.get('ToDate');
                    }

                }



                else
                {
                    alert('აირჩიეთ შუალედი');

                }


            }
        });

        win.setData();
        win.show();
    },

    getValue: function() {

        var obj = !(this.fromDate && this.toDate) ? null : {
            FromDate: this.fromDate,
            ToDate: this.toDate
        };

        return obj;


    }

});