//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance : IEntity
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> OutputPrice { get; set; }
        public Nullable<double> InputPrice { get; set; }
        public Nullable<int> SizeUnitID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> CurrentAmount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> RealPrice { get; set; }
    
        public virtual SizeUnit SizeUnit { get; set; }
    }
}
