//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseType : IEntity
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public int CourseTypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual SystemDictionaryValue SystemDictionaryValue { get; set; }
    }
}
