//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours : IEntity
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CreateDate { get; set; }
        public string CourseStatusID { get; set; }
        public Nullable<int> CreditCount { get; set; }
        public Nullable<int> HourCount { get; set; }
        public Nullable<int> CourseType { get; set; }
        public Nullable<int> OwnerOrganizationalUnitID { get; set; }
    }
}
