//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class droebiti_natia : IEntity
    {
        public int ProgramBlockUnitID { get; set; }
        public string Name { get; set; }
        public int ProgramID { get; set; }
        public Nullable<int> OwnerOrganizationalUnitID { get; set; }
        public bool IsActive { get; set; }
        public int ID { get; set; }
        public string Code { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CourseStatusID { get; set; }
        public int CreditCount { get; set; }
        public int TotalHourCount { get; set; }
        public int CourseTypeID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public int SemesterTypeID { get; set; }
        public int StudyLanguageID { get; set; }
        public int AssessmentSchemeID { get; set; }
        public int ProgramTypeID { get; set; }
    }
}
