//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem : IEntity
    {
        public MenuItem()
        {
            this.MenuItems1 = new HashSet<MenuItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> FormID { get; set; }
        public string IconUrl { get; set; }
        public Nullable<bool> IsLeaf { get; set; }
        public Nullable<int> IndexNumber { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual ICollection<MenuItem> MenuItems1 { get; set; }
        public virtual MenuItem MenuItem1 { get; set; }
    }
}
