//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product : IEntity
    {
        public Product()
        {
            this.Details = new HashSet<Detail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> OutputPrice { get; set; }
        public bool Deleted { get; set; }
        public Nullable<double> InputPrice { get; set; }
        public Nullable<int> SizeUnitID { get; set; }
        public Nullable<int> CurrentAmount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public int BalanceID { get; set; }
        public Nullable<double> RealPrice { get; set; }
    
        public virtual ICollection<Detail> Details { get; set; }
        public virtual SizeUnit SizeUnit { get; set; }
    }
}
