//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryStudent
    {
        public RegistryStudent()
        {
            this.RegistryStudentFingerTemplates = new HashSet<RegistryStudentFingerTemplate>();
            this.RegistryStudentImages = new HashSet<RegistryStudentImage>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int GenderID { get; set; }
        public int StatusID { get; set; }
        public string PassportNumber { get; set; }
        public string PersonalNumber { get; set; }
        public Nullable<int> CitizenTypeID { get; set; }
    
        public virtual ICollection<RegistryStudentFingerTemplate> RegistryStudentFingerTemplates { get; set; }
        public virtual ICollection<RegistryStudentImage> RegistryStudentImages { get; set; }
        public virtual SystemDictionaryValue SystemDictionaryValue { get; set; }
    }
}
