//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryStudentFingerTemplate
    {
        public int ID { get; set; }
        public int RegistryStudentID { get; set; }
        public int FingerID { get; set; }
        public byte[] FingerTemplate { get; set; }
    
        public virtual RegistryStudent RegistryStudent { get; set; }
        public virtual SystemDictionaryValue SystemDictionaryValue { get; set; }
    }
}
