//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeUnit : IEntity
    {
        public SizeUnit()
        {
            this.Balances = new HashSet<Balance>();
            this.Details = new HashSet<Detail>();
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Balance> Balances { get; set; }
        public virtual ICollection<Detail> Details { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
