/*
 * File: app/model/ProgramConfigModel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.model.ProgramConfigModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.association.HasMany',
        'Ext.data.Field'
    ],
    uses: [
        'SIS.model.ProgramCourseConfigModel',
        'SIS.model.OrganizationalUnitModel'
    ],

    hasMany: [
        {
            model: 'SIS.model.ProgramCourseConfigModel',
            name: 'ProgramCourseConfigs'
        },
        {
            model: 'SIS.model.OrganizationalUnitModel',
            name: 'AdditionalOrganizationalUnits'
        }
    ],

    fields: [
        {
            name: 'OrganizationalUnitID'
        },
        {
            name: 'OrganizationalUnitName'
        },
        {
            name: 'CreateDate'
        },
        {
            name: 'StartDate'
        },
        {
            name: 'EndDate'
        },
        {
            name: 'IsActive'
        },
        {
            name: 'ProgramID'
        },
        {
            name: 'ProgramName'
        },
        {
            name: 'ProgramConfigStatusID',
            type: 'int'
        },
        {
            name: 'ProgramConfigStatusName'
        },
        {
            name: 'ID'
        }
    ]
});