/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    models: [
        'GroupActionsTreeModel',
        'MenuItemsModel',
        'UsersModel',
        'SizeUnitModel',
        'ProductModel',
        'CustomerModel',
        'tblgadamzidvelebi',
        'tbltranspsaxe',
        'tblzomisertModel',
        'DistributorModel',
        'DetailModel',
        'BalanceModel',
        'IncomeProductModel',
        'OperationModel',
        'OutcomeProductModel',
        'ExcelProductModel'
    ],
    stores: [
        'AllProductStore',
        'ProductArrayStore',
        'AllCustomerStore',
        'AllDistributorStore',
        'AllDetailStore',
        'AllBalanceStore',
        'IncomeProductArrayStore',
        'ActiveCustomerStore',
        'ActiveProductStore',
        'ActiveDistributorStore'
    ],
    views: [
        'ProgramSearchInfo',
        'FacConfigRO',
        'ProgramManagerConfigInfoPanel',
        'MyForm2',
        'MyPanel23',
        'UsersAddEditWindow',
        'UserGroupsCombo',
        'GroupActionsMainPanel',
        'MyViewport',
        'AddSizeUnit',
        'Customers',
        'RS',
        'AddCustomer',
        'Distributors',
        'AddDistributor',
        'Products',
        'AddProduct',
        'InputProducts',
        'OutputProducts',
        'Balance',
        'IncomeProducts',
        'OutcomeProducts',
        'DateRangeSelectorForm'
    ],
    name: 'SIS'
});
