/*
 * File: app/store/AllDetailStore.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.store.AllDetailStore', {
    extend: 'Ext.data.Store',

    requires: [
        'SIS.model.DetailModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            model: 'SIS.model.DetailModel',
            storeId: 'AllDetailStore',
            proxy: {
                type: 'ajax',
                type: 'jsonajax',
                url: '/Home/GetDetailsByConditions',
                reader: {
                    type: 'json',
                    root: 'root',
                    totalProperty: 'count'
                }
            }
        }, cfg)]);
    }
});