/*
 * File: app/view/DateRangeSelectorForm.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.DateRangeSelectorForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.daterangeform',

    requires: [
        'Ext.container.Container',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    height: 321,
    itemId: 'btnAccept',
    width: 447,
    title: 'თარიღის შუალედი',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            keyMapConfig: {
                bindings: [
                    {
                        ctrl: false,
                        key: Ext.EventObject.ENTER,
                        btnItemId: 'btnAccept'
                    }
                ]
            },
            items: [
                {
                    xtype: 'container',
                    height: 242,
                    width: 437,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 248,
                            width: 218,
                            items: [
                                {
                                    xtype: 'label',
                                    margin: '5 0 0 60',
                                    text: 'საწყისი თარიღი'
                                },
                                {
                                    xtype: 'datepicker',
                                    itemId: 'pStartDate'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 248,
                            width: 218,
                            items: [
                                {
                                    xtype: 'label',
                                    margin: '5 0 0 60',
                                    text: 'ბოლო თარიღი'
                                },
                                {
                                    xtype: 'datepicker',
                                    itemId: 'pEndDate'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 27,
                    margin: '5 0 0 0 ',
                    width: 437,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 47,
                            html: 'ბოლო: <a href=\'#\'> კვირა </a> &nbsp; <a href=\'#\'> თვე </a> &nbsp; <a href=\'#\'> წელი </a>',
                            margin: '0 0 0 5',
                            width: 331,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            }
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                var win = button.up('daterangeform');


                                var result = win.validate();

                                if(!result.success)
                                {
                                    MessageBox('', result.msg);
                                    return;
                                }



                                var dialogResult = win.save(win.getData());

                                if(dialogResult == EnumDialogResult.Success || IsNullOrEmpty(dialogResult))
                                {
                                    win.close();
                                }
                            },
                            height: 64,
                            itemId: 'btnAccept',
                            width: 95,
                            iconCls: 'icon-accept',
                            text: 'დასტური'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    getData: function() {
        var win = this;

        if(this.dateRange == null){
            this.dateRange = Ext.create('SIS.model.DateRangeSelectModel');
        }

        var pStartDate = FindControl(win, 'pStartDate');

        var pEndDate = FindControl(win, 'pEndDate');

        //this.dateRange.set('FromDate', GetComponent('StartDate3',this).getValue());
        //this.dateRange.set('ToDate', GetComponent('EndDate',this).getValue());

        //this.dateRange.set('Range',  this.dateRange.get('FromDate') + ' ' + '-' + ' '+ this.dateRange.get('ToDate'));


        win.dateRange.data.FromDate = pStartDate.getValue();

        win.dateRange.data.ToDate = pEndDate.getValue();


        return win.dateRange;

    },

    setData: function() {
        var win = this;

        if(this.dateRange == null){
            this.dateRange = Ext.create('SIS.model.DateRangeSelectModel');
        }


        var pStartDate = FindControl(win, 'pStartDate');

        var pEndDate = FindControl(win, 'pEndDate');

        pStartDate.selectToday();

        pEndDate.selectToday();
    },

    validate: function() {

        var win = this;

        var result = {success: true};

        var pStartDate = FindControl(win, 'pStartDate');

        var pEndDate = FindControl(win, 'pEndDate');


        if(IsNullOrEmpty(pStartDate.getValue))
        {
            result.success = false;
            result.msg = 'აირჩიეთ საწყისი თარიღი!';
        }

        if(IsNullOrEmpty(pEndDate.getValue()))
        {
            result.success = false;
            result.msg = 'აირჩიეთ ბოლო თარიღი!';
        }


        if(pStartDate.getValue() > pEndDate.getValue())
        {
            result.success = false;
            result.msg = 'არასწორი შუალედი!';
        }




        return result;
    }

});