/*
 * File: app/view/MyTreePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.MyTreePanel', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.mytreepanel',

    requires: [
        'Ext.tree.View'
    ],

    itemId: 'MenuTree',
    width: 280,
    collapseDirection: 'left',
    collapsed: false,
    iconCls: 'menu',
    title: 'მთავარი მენიუ',
    store: 'MyTreeStore',
    animate: true,
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            listeners: {
                select: {
                    fn: me.onMenuTreeSelect,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onMenuTreeSelect: function(rowmodel, record, index, eOpts) {
        /*
            var menuTree = this;
            //alert(menuTree.getId());
            //menuTree.setDisabled(true);
            //rowmodel.expand();
            var rec = menuTree.getSelectedRecord();
            rec.expandChildren();
        */


    }

});