/*
 * File: app/view/ProgramConfigUnitsPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.ProgramConfigUnitsPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.programconfigunits',

    requires: [
        'SIS.view.OrgUnitsCombo',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.column.CheckColumn',
        'Ext.button.Button'
    ],

    border: false,
    layout: 'fit',
    header: false,
    title: 'პროგრამის შემსრულებელი ფაკულტეტები',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: false,
                    autoScroll: true,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        padding: 10
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            padding: 5,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'პროგრამა',
                                    value: 'Display Field'
                                },
                                {
                                    xtype: 'comboorgunits',
                                    ParentCode: 'GTU',
                                    itemId: 'cmbMainOrg',
                                    fieldLabel: 'ძირითადი ფაკულტეტი',
                                    anchor: '100%',
                                    listeners: {
                                        beforedeselect: {
                                            fn: me.onMycombobox33BeforeDeselect,
                                            scope: me
                                        },
                                        select: {
                                            fn: me.onMycombobox33Select,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'comboorgunits',
                                    ParentCode: 'GTU',
                                    itemId: 'cmbAuxOrg',
                                    fieldLabel: 'თანამონაწილე ფაკულტეტები',
                                    anchor: '100%',
                                    listeners: {
                                        beforedeselect: {
                                            fn: me.onMycombobox33BeforeDeselect1,
                                            scope: me
                                        },
                                        select: {
                                            fn: me.onMycombobox33Select1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            minHeight: 400,
                            title: 'მოდულები',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    storeClassName: 'SIS.store.ProgramConfigCourseStore',
                                    flex: 1,
                                    itemId: 'grdProgramModuleConfig',
                                    header: false,
                                    title: 'My Grid Panel',
                                    store: 'ProgramConfigCourseStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'დასახელება',
                                            flex: 2
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'ტიპი',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'შემსრულებელი',
                                            flex: 1,
                                            editor: {
                                                xtype: 'comboorgunits',
                                                ParentCode: 'GTU'
                                            }
                                        }
                                    ],
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.CellEditing', {

                                        })
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    layout: 'fit',
                                    title: 'საფაკულტეტო სასწავლო კურსები',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            storeClassName: 'SIS.store.ProgramConfigCourseStore',
                                            itemId: 'grdProgramConfigCourses',
                                            header: false,
                                            title: 'My Grid Panel',
                                            store: 'ProgramConfigCourseStore',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    text: 'დასახელება',
                                                    flex: 2
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    text: 'კოდი',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    disabled: true,
                                                    text: 'საუნივერსიტეტო',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    text: 'შემსრულებელი',
                                                    flex: 1,
                                                    editor: {
                                                        xtype: 'comboorgunits',
                                                        ParentCode: 'GTU'
                                                    }
                                                }
                                            ],
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.CellEditing', {

                                                })
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            layout: 'fit',
                            title: 'თავისუფალი კომპონენტი',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    storeClassName: 'SIS.store.ProgramConfigCourseStore',
                                    itemId: 'grdFreeComponentConfig',
                                    minHeight: 200,
                                    header: false,
                                    title: 'My Grid Panel',
                                    store: 'ProgramConfigCourseStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'დასახელება',
                                            flex: 2
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'კოდი',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'checkcolumn',
                                            disabled: true,
                                            draggable: false,
                                            text: 'საუნივერსიტეტო',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'შემსრულებელი',
                                            flex: 1,
                                            editor: {
                                                xtype: 'comboorgunits',
                                                ParentCode: 'GTU'
                                            }
                                        }
                                    ],
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.CellEditing', {

                                        })
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            padding: 5,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    disableOnReadOnly: false,
                                    userActionId: 'ACTIVATE_PROGRAM_CONFIG',
                                    itemId: 'btnSetAct',
                                    margin: '0 0 0 5',
                                    text: 'გააქტიურება'
                                },
                                {
                                    xtype: 'button',
                                    userActionId: 'RETURN_PROGRAM_CONFIG',
                                    itemId: 'btnSetEdit',
                                    margin: '0 0 0 5',
                                    text: 'დაბრუნება'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'btnPrint',
                                    text: 'ბეჭდვა'
                                },
                                {
                                    xtype: 'button',
                                    disableOnReadOnly: true,
                                    userActionId: 'PRESENT_PROGRAM_CONFIG',
                                    itemId: 'btnPresent',
                                    margin: '0 0 0 5',
                                    text: 'წარდგენა'
                                },
                                {
                                    xtype: 'button',
                                    disableOnReadOnly: true,
                                    userActionId: 'SAVE_PROGRAM_CONFIG',
                                    itemId: 'btnSave',
                                    margin: '0 0 0 5',
                                    text: 'შენახვა'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCancel',
                                    margin: '0 0 0 5',
                                    text: 'დახურვა'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onMycombobox33BeforeDeselect: function(combo, record, index, eOpts) {
        //Check if org Unit is present in Aux units
            //If present, CheckAction()
                    //If true SetDelete()
                    //else return false;
            //else
                //Check for conflicting records
                    //get/Check BlockConfigs - var ConflictingBlockConfigs
                        //if true CheckAction('One or more block configs are using this org unit. Proceeding will set their unit to chosen)
                            //if(true) - foreach var item in ConflictingBlockConfigs item.set('OrganizationalUnitId','')
                            //				foreach var unitconfig in item getConflicts() foreach Conflict .set('','');

    },

    onMycombobox33Select: function(combo, records, eOpts) {

    },

    onMycombobox33BeforeDeselect1: function(combo, record, index, eOpts) {

    },

    onMycombobox33Select1: function(combo, records, eOpts) {

    },

    getRecord: function() {

    },

    setRecord: function(model) {
        var form=this;
        form.formModel=model;
        form.originalModel=CloneModel(model);

        var gridModules=Findcontrol(form,'grdProgramModuleConfig');
        var gridModules=Findcontrol(form,'grdProgramConfigCourses');
        var gridModules=Findcontrol(form,'grdFreeComponentConfig');
    },

    getObjectAllowedActions: function() {

    }

});