/*
 * File: app/view/StaffSearchPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.view.StaffSearchPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.staffsearchpanel',

    requires: [
        'SIS.view.DateRangeSelector',
        'SIS.view.DateRangeSelector1'
    ],

    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    bodyPadding: 5,
    title: 'სტუდენტის ძებნა',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    width: 640,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 5,
                    title: '',
                    items: [
                        {
                            xtype: 'fieldset',
                            itemId: 'fldstFullSearch',
                            layout: {
                                align: 'stretch',
                                padding: 5,
                                type: 'hbox'
                            },
                            collapsible: true,
                            title: 'გაფართოებული ძებნა',
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 2,
                                    width: 745,
                                    layout: {
                                        align: 'stretch',
                                        padding: '0 5 0 0',
                                        type: 'vbox'
                                    },
                                    fieldLabel: '',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtPersonalNumber',
                                            width: 244,
                                            fieldLabel: '',
                                            emptyText: 'პირადი ნომერი/ პასპორტის ნომერი'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtFirstName',
                                            fieldLabel: '',
                                            emptyText: 'სახელი'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'txtLastName',
                                            fieldLabel: '',
                                            emptyText: 'გვარი'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 2,
                                    width: 745,
                                    layout: {
                                        align: 'stretch',
                                        padding: '0 5 0 0',
                                        type: 'vbox'
                                    },
                                    fieldLabel: '',
                                    items: [
                                        {
                                            xtype: 'daterangefield',
                                            itemId: 'dtrngBirthDate',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'daterangeselector1',
                                            itemId: 'dtrngRegistrationDate',
                                            emptyText: 'მუშაობის დაწყების თარიღი',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'combobox',
                                            dictionaryID: '5',
                                            storeClassName: 'SIS.store.DictionaryValueStore',
                                            itemId: 'cmbPositionTypeID',
                                            fieldLabel: '',
                                            emptyText: 'თანამდებობის ტიპი',
                                            displayField: 'Name',
                                            store: 'DictionaryValueStore',
                                            valueField: 'ID'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    width: 745,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    fieldLabel: '',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            dictionaryID: '1',
                                            storeClassName: 'SIS.store.DictionaryValueStore',
                                            itemId: 'cmbGender',
                                            fieldLabel: '',
                                            emptyText: 'სქესი',
                                            displayField: 'Name',
                                            store: 'DictionaryValueStore',
                                            valueField: 'ID'
                                        },
                                        {
                                            xtype: 'combobox',
                                            storeClassName: 'SIS.store.DictionaryValueStore',
                                            dictionaryID: '4',
                                            itemId: 'cmbStaffStatusID',
                                            fieldLabel: '',
                                            emptyText: 'სტატუსი',
                                            displayField: 'Name',
                                            store: 'DictionaryValueStore',
                                            valueField: 'ID'
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            width: 345,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            fieldLabel: '',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    width: 40,
                                                    layout: {
                                                        type: 'vbox'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnFullSearch',
                                                    iconCls: 'icon-search'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnFullSearchClear',
                                                    margin: '0 0 0 5',
                                                    iconCls: 'icon-clear'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            width: 207,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'txtQSearch',
                                    margin: '',
                                    width: 455,
                                    fieldLabel: '',
                                    labelAlign: 'right',
                                    emptyText: 'სწრაფი ძებნა'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnQsearch',
                                    margin: '0 0 0 5',
                                    iconCls: 'icon-search'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnQsearchClear',
                                    margin: '0 15 0 5',
                                    iconCls: 'icon-clear'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            height: 323,
                            width: 629,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'ძებნის შედეგი',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    storeClassName: 'SIS.store.MyStudentStore',
                                    flex: 1,
                                    height: 317,
                                    itemId: 'grdStaffSearch',
                                    title: '',
                                    store: 'MyStudentStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'PersonalNumber',
                                            text: 'პირადი #'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'FirstName',
                                            text: 'სახელი',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'LastName',
                                            text: 'გვარი',
                                            flex: 2
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'StatusName',
                                            text: 'სტატუსი'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'მოქალაქეობა'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            width: 24,
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                        Ext.Msg.alert('', 'როგორ მინდა კარგად გავაკეთო ყველა დავალება :)');
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'GenderName',
                                            text: 'სქესი'
                                        }
                                    ],
                                    viewConfig: {
                                        height: 50000,
                                        itemId: 'GrdSt',
                                        width: 50000
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            beforePageText: 'გვერდი',
                                            displayInfo: true,
                                            displayMsg: 'ნაჩვენებია {0} - {1} სულ  {2}',
                                            store: 'MyStudentStore',
                                            layout: {
                                                padding: 2,
                                                type: 'hbox'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    width: 200,
                    layout: {
                        type: 'anchor'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'image',
                            baseCls: '',
                            height: 201,
                            itemId: 'image_st',
                            width: 201,
                            imgCls: 'myimg',
                            src: ''
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});