/*
 * File: app/controller/TreeController.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIS.controller.TreeController', {
    extend: 'Ext.app.Controller',

    models: [
        'TreeModel'
    ],
    stores: [
        'MyTreeStore'
    ],
    views: [
        'MyTreePanel'
    ],

    refs: [
        {
            ref: 'navtree',
            selector: 'mytreepanel#MenuTree'
        }
    ],

    NodeSelected: function(dataview, record, item, index, e, eOpts) {
        if(record.data.FormID!==null&&record.data.FormID!==undefined)
        {
            var Form=record.data.Form;

            var conf = {title:Form.Title,closable:true,closeAction:'destroy'};

            var View=Ext.create(Form.ClassName,{});

            NewTab(View, Form.Title);
        }

        if(record.get('id') === 14){
            fileDownload('/Home/GetAttachmentFile',{
                windowid: GetWindowId()
            });
        }
    },

    onTreepanelAfterRender: function(component, eOpts) {
        component.expandAll();
    },

    init: function(application) {
        this.control({
            "#MenuTree": {
                itemclick: this.NodeSelected,
                afterrender: this.onTreepanelAfterRender
            }
        });
    }

});
